### ISSUE TITLE
Extra rows for first PR after release

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/asv-formatter#5]
![Screenshot 2023-08-16 164450](https://github.com/lincc-frameworks/asv-formatter/assets/113376043/f2204d5d-af9b-4d3f-8438-d51c513c22db)

The first two rows show commit tags, then indicates that the "before" is a versioned commit (this is the first PR after tagging a new release). This is taking up valuable vertical space in the table, and it might be extract these rows into a single text line above or below the table, e.g. 

```
Comparing commit [abe797f] (<v0.1.2>) and [0304e9]. Click [here] to view all benchmarks.

| Before | After | Ratio | Method   |
| ------ | ----- | ----- | -------- |
|    14s |   10s |   400 | nonsense |
```

This additional row would presumably also show up for commits to main and nightly runs after tagged releases.

**Comment by drewoldag** [comment]
Need to test with the latest version of ASV, and see if this is still an issue or not.

**Comment by camposandro** [comment]
I investigated this behavior and with the previous versions of `asv` (< 0.6) we would indeed get an extra row specifying the version tags. On the latest versions, however, they seem to appear next to the "Before" and "After" column headers, the same way branch names usually appear when opening a PR against main.

I agree that we should extract these values, especially because branch names can get quite large. I just opened a PR to extract them and add them to a one-liner before the table.

### Input table

All benchmarks:

| Change   | Before [a4e3082d] <0\.0\.1\~59>   | After [6f9dea7d] <new\-branch>   | Ratio   | Benchmark (Parameter)              |
|----------|--------------------------------|---------------------------------|---------|------------------------------------|
|          | 724±600ms                      | 1.83±0.4s                       | ~2.53   | benchmarks.TimeSuite.time_range    |
|          | 671±300ms                      | 1.55±0.7s                       | ~2.30   | benchmarks.TimeSuite.time_keys     |
|          | 1.25±0.3s                      | 2.35±1s                         | ~1.88   | benchmarks.TimeSuite.time_xrange   |
|          | 1.26±0.4s                      | 1.15±0.8s                       | 0.91    | benchmarks.TimeSuite.time_iterkeys |
| -        | 5.98k                          | 3.1k                            | 0.52    | benchmarks.MemSuite.mem_list       |


### Formatted table

Comparing **<0\.0\.1\~59>** and **<new\-branch>**

| Before [a4e3082d]              | After [6f9dea7d]                | Ratio   | Benchmark (Parameter)              |
|--------------------------------|---------------------------------|---------|------------------------------------|
| 724±600ms                      | 1.83±0.4s                       | ~2.53   | benchmarks.TimeSuite.time_range    |
| 671±300ms                      | 1.55±0.7s                       | ~2.30   | benchmarks.TimeSuite.time_keys     |
| 1.25±0.3s                      | 2.35±1s                         | ~1.88   | benchmarks.TimeSuite.time_xrange   |
| 1.26±0.4s                      | 1.15±0.8s                       | 0.91    | benchmarks.TimeSuite.time_iterkeys |
| 5.98k                          | 3.1k                            | 0.52    | benchmarks.MemSuite.mem_list       |
